### PR TITLE
add rio-tiler 

### PR DESCRIPTION
**Pull request by vincentsarago**
:wave: @cholmes 
just a shameless plug about rio-tiler and landsat-tiler :-) 

🙏

### CODE REVIEW

**Comment by cholmes** [comment]
Very cool, I hadn't heard of it, but it looks great. If you want to plug it more a tutorial on making it work with any COG would be awesome. Something similar to http://www.cogeo.org/qgis-tutorial.html I'll put those at the top of the list, so people get a sense of how to actually use COG's.

**Comment by vincentsarago** [comment]
FYI: We did a blob post about it https://blog.mapbox.com/combining-the-power-of-aws-lambda-and-rasterio-8ffd3648c348
and we have a live demo of landsat-tiler on https://viewer.remotepixel.ca

**Comment by cholmes** [comment]
Oh cool! Feel free to make a PR with links to both of those for the main page, especially the live
demo. And you can also move it to right under 'marblecutter' in the list - those with links to tutorials and live online demonstrations get priority :)

Or I can find some time to update it next week.

**Comment by vincentsarago** [comment]
Excellent I'll do it

**Pull request merged**
